---
sidebar: sidebar 
permalink: anthos/anthos-trident-ontap-nfs.html 
keywords: Trident, Trident, ONTAP, AFF, FAS, NFS 
summary: Para habilitar la integración de Trident con el sistema de almacenamiento NetApp ONTAP , debe crear un backend que permita la comunicación con el sistema de almacenamiento. 
---
= Configuración de NFS de NetApp ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Para habilitar la integración de Trident con el sistema de almacenamiento NetApp ONTAP , debe crear un backend que permita la comunicación con el sistema de almacenamiento.

. Hay archivos de backend de muestra disponibles en el archivo de instalación descargado en `sample-input` jerarquía de carpetas.  Para los sistemas NetApp ONTAP que prestan servicio a NFS, copie el archivo `backend-ontap-nas.json` archivo a su directorio de trabajo y edite el archivo.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ cp sample-input/backends-samples/ontap-nas/backend-ontap-nas.json ./
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ vi backend-ontap-nas.json
----
. Edite los valores backendName, managementLIF, dataLIF, svm, username y password en este archivo.
+
[listing]
----
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "backendName": "ontap-nas+10.61.181.221",
    "managementLIF": "172.21.224.201",
    "dataLIF": "10.61.181.221",
    "svm": "trident_svm",
    "username": "cluster-admin",
    "password": "password"
}
----
+

NOTE: Se recomienda definir el valor backendName personalizado como una combinación de storageDriverName y dataLIF que sirve NFS para una fácil identificación.

. Con este archivo backend en su lugar, ejecute el siguiente comando para crear su primer backend.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ ./tridentctl -n trident create backend -f backend-ontap-nas.json
+-------------------------+----------------+--------------------------------------+--------+---------+
|          NAME           | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+-------------------------+----------------+--------------------------------------+--------+---------+
| ontap-nas+10.61.181.221 | ontap-nas      | be7a619d-c81d-445c-b80c-5c87a73c5b1e | online |       0 |
+-------------------------+----------------+--------------------------------------+--------+---------+
----
. Con el backend creado, a continuación debes crear una clase de almacenamiento.  Al igual que con el backend, hay un archivo de clase de almacenamiento de muestra que se puede editar para el entorno disponible en la carpeta sample-inputs.  Cópielo en el directorio de trabajo y realice las modificaciones necesarias para reflejar el backend creado.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ cp sample-input/storage-class-samples/storage-class-csi.yaml.templ ./storage-class-basic.yaml
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ vi storage-class-basic.yaml
----
. La única edición que se debe realizar en este archivo es definir el `backendType` valor al nombre del controlador de almacenamiento desde el backend recién creado.  Tenga en cuenta también el valor del campo de nombre, al que se debe hacer referencia en un paso posterior.
+
[listing]
----
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: basic-csi
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
----
+

NOTE: Hay un campo opcional llamado `fsType` que se define en este archivo.  Esta línea se puede eliminar en los backends de NFS.

. Ejecutar el `kubectl` Comando para crear la clase de almacenamiento.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ kubectl create -f storage-class-basic.yaml
storageclass.storage.k8s.io/basic-csi created
----
. Una vez creada la clase de almacenamiento, deberá crear la primera reclamación de volumen persistente (PVC).  Hay una muestra `pvc-basic.yaml` archivo que se puede utilizar para realizar esta acción y que también se encuentra en sample-inputs.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ cp sample-input/pvc-samples/pvc-basic.yaml ./
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ vi pvc-basic.yaml
----
. La única edición que se debe realizar en este archivo es asegurarse de que `storageClassName` El campo coincide con el recién creado.  La definición de PVC se puede personalizar aún más según lo requiera la carga de trabajo que se aprovisionará.
+
[listing]
----
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: basic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: basic-csi
----
. Cree el PVC emitiendo el `kubectl` dominio.  La creación puede tardar algún tiempo dependiendo del tamaño del volumen de respaldo que se esté creando, por lo que puedes observar el proceso a medida que se completa.
+
[listing]
----
[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ kubectl create -f pvc-basic.yaml
persistentvolumeclaim/basic created

[ubuntu@gke-admin-ws-2022-05-03 trident-installer]$ kubectl get pvc
NAME    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
basic   Bound    pvc-b4370d37-0fa4-4c17-bd86-94f96c94b42d   1Gi        RWO            basic-csi      7s
----

