---
sidebar: sidebar 
permalink: anthos/anthos-metallb.html 
summary: Esta página detalla las instrucciones de instalación y configuración del balanceador de carga MetalLB. 
keywords: Anthos, Kubernetes, MetalLB, LoadBalancer, 
---
= Instalación de balanceadores de carga MetalLB
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Esta página enumera las instrucciones de instalación y configuración del balanceador de carga administrado MetalLB.



== Instalación del balanceador de carga MetalLB

El balanceador de carga MetalLB está completamente integrado con Anthos Clusters en VMware y tiene una implementación automatizada realizada como parte de las configuraciones del clúster de administrador y usuario a partir de la versión 1.11.  Hay bloques de texto en los respectivos `cluster.yaml` archivos de configuración que debe modificar para proporcionar información del balanceador de carga.  Se aloja automáticamente en su clúster Anthos en lugar de requerir la implementación de recursos externos como las otras soluciones de balanceador de carga compatibles.  También permite crear un ip-pool que asigna direcciones automáticamente con la creación de servicios Kubernetes de tipo balanceador de carga en clusters que no corren en un proveedor de nube.



== Integración con Anthos

Al habilitar el balanceador de carga MetalLB para el administrador de Anthos, debe modificar algunas líneas en el archivo `loadBalancer:` sección que existe en el `admin-cluster.yaml` archivo.  Los únicos valores que debes modificar son los que debes establecer `controlPlaneVIP:` dirección y luego configure el `kind:` como MetalLB.  Vea el siguiente fragmento de código para ver un ejemplo:

[listing]
----
# (Required) Load balancer configuration
loadBalancer:
  # (Required) The VIPs to use for load balancing
  vips:
    # Used to connect to the Kubernetes API
    controlPlaneVIP: "10.61.181.230"
    # # (Optional) Used for admin cluster addons (needed for multi cluster features). Must
    # # be the same across clusters
    # addonsVIP: ""
  # (Required) Which load balancer to use "F5BigIP" "Seesaw" "ManualLB" or "MetalLB".
  # Uncomment the corresponding field below to provide the detailed spec
  kind: MetalLB
----
Al habilitar el balanceador de carga MetalLB para los clústeres de usuarios de Anthos, hay dos áreas en cada uno `user-cluster.yaml` archivo que debes actualizar.  En primer lugar, de manera similar a la `admin-cluster.yaml` archivo, debes modificar el `controlPlaneVIP:` , `ingressVIP:` , y `kind:` valores en el `loadBalancer:` sección.  Vea el siguiente fragmento de código para ver un ejemplo:

[listing]
----
loadBalancer:
  # (Required) The VIPs to use for load balancing
  vips:
    # Used to connect to the Kubernetes API
    controlPlaneVIP: "10.61.181.240"
    # Shared by all services for ingress traffic
    ingressVIP: "10.61.181.244"
  # (Required) Which load balancer to use "F5BigIP" "Seesaw" "ManualLB" or "MetalLB".
  # Uncomment the corresponding field below to provide the detailed spec
  kind: MetalLB
----

NOTE: La dirección IP de ingressVIP debe existir dentro del grupo de direcciones IP asignadas al balanceador de carga MetalLB más adelante en la configuración.

A continuación, deberás navegar hasta el `metalLB:` subsección y modificar la `addressPools:` sección nombrando la piscina en el `- name:` variable.  También debe crear un grupo de direcciones IP que MetalLB pueda asignar a servicios de tipo LoadBalancer proporcionando un rango a los `addresses:` variable.

[listing]
----
# # (Required when using "MetalLB" kind in user clusters) Specify the MetalLB config
 metalLB:
 #   # (Required) A list of non-overlapping IP pools used by load balancer typed services.
 #   # Must include ingressVIP of the cluster.
    addressPools:
 #   # (Required) Name of the address pool
    - name: "default"
 #     # (Required) The addresses that are part of this pool. Each address must be either
 #     # in the CIDR form (1.2.3.0/24) or range form (1.2.3.1-1.2.3.5).
      addresses:
      - "10.61.181.244-10.61.181.249"
----

NOTE: El grupo de direcciones se puede proporcionar como un rango, como en el ejemplo, limitándolo a una cantidad de direcciones en una subred particular, o se puede proporcionar como una notación CIDR si toda la subred está disponible.

. Cuando se crean servicios Kubernetes del tipo LoadBalancer, MetalLB asigna automáticamente una IP externa a los servicios y anuncia la dirección IP respondiendo a las solicitudes ARP.

