---
sidebar: sidebar 
permalink: anthos/anthos-solution-overview.html 
keywords: NVA-1165, Anthos, GKE, Netapp, Trident 
summary: Este documento de referencia proporciona la validación de la implementación de la solución Anthos con NetApp , implementada en múltiples entornos de centros de datos según lo validado por NetApp y nuestros socios de ingeniería. 
---
= NVA-1165: Anthos con NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


Banu Sundhar y Suresh Thoppay, NetApp

[role="lead"]
Este documento de referencia proporciona validación de la implementación de la solución Anthos con NetApp por parte de NetApp y nuestros socios de ingeniería cuando se implementa en múltiples entornos de centros de datos.  También detalla la integración del almacenamiento con los sistemas de almacenamiento NetApp mediante el uso del orquestador de almacenamiento Trident para la gestión del almacenamiento persistente.  Por último, exploramos y documentamos una serie de validaciones de soluciones y casos de uso del mundo real.



== Casos de uso

La solución Anthos con NetApp está diseñada para ofrecer un valor excepcional a los clientes con los siguientes casos de uso:

* Entorno Anthos fácil de implementar y administrar implementado utilizando el software proporcionado `bmctl` herramienta sobre metal desnudo o el `gkectl` herramienta en VMware vSphere.
* Potencia combinada de contenedores empresariales y cargas de trabajo virtualizadas con Anthos implementado virtualmente en vSphere o en hardware con https://cloud.google.com/anthos/clusters/docs/bare-metal/1.9/how-to/vm-workloads["kubevirt"^] .
* Configuración del mundo real y casos de uso que resaltan las características de Anthos cuando se utiliza con almacenamiento de NetApp y Trident, el orquestador de almacenamiento de código abierto para Kubernetes.




== Valor empresarial

Las empresas están adoptando cada vez más prácticas de DevOps para crear nuevos productos, acortar los ciclos de lanzamiento y agregar rápidamente nuevas funciones.  Debido a su naturaleza ágil innata, los contenedores y los microservicios juegan un papel crucial en el apoyo a las prácticas de DevOps.  Sin embargo, practicar DevOps a escala de producción en un entorno empresarial presenta sus propios desafíos e impone ciertos requisitos en la infraestructura subyacente, como los siguientes:

* Alta disponibilidad en todas las capas de la pila
* Facilidad de procedimientos de implementación
* Operaciones y actualizaciones sin interrupciones
* Infraestructura programable e impulsada por API para mantenerse al día con la agilidad de los microservicios
* Multitenencia con garantías de rendimiento
* La capacidad de ejecutar cargas de trabajo virtualizadas y en contenedores simultáneamente
* La capacidad de escalar la infraestructura de forma independiente en función de las demandas de carga de trabajo


La solución Anthos con NetApp reconoce estos desafíos y presenta una solución que ayuda a abordar cada inquietud al implementar la implementación totalmente automatizada de Anthos en las instalaciones en el entorno de centro de datos elegido por el cliente.



== Descripción general de la tecnología

La solución Anthos con NetApp se compone de los siguientes componentes principales:



=== Anthos On Prem

Anthos On Prem es una plataforma Kubernetes empresarial totalmente compatible que se puede implementar en el hipervisor VMware vSphere o en una infraestructura física de su elección.

Para obtener más información sobre Anthos, consulte el sitio web de Anthos ubicado https://cloud.google.com/anthos["aquí"^] .



=== Sistemas de almacenamiento NetApp

NetApp tiene varios sistemas de almacenamiento perfectos para centros de datos empresariales e implementaciones de nube híbrida.  La cartera de NetApp incluye NetApp ONTAP, Cloud Volumes ONTAP, Google Cloud NetApp Volumes, Azure NetApp Files y FSx ONTAP para sistemas de almacenamiento NetApp ONTAP , todos los cuales pueden proporcionar almacenamiento persistente para aplicaciones en contenedores.

Para obtener más información, visite el sitio web de NetApp https://www.netapp.com["aquí"] .



=== Integraciones de almacenamiento de NetApp

Trident es un orquestador de almacenamiento de código abierto y totalmente compatible con contenedores y distribuciones de Kubernetes, incluido Anthos.

Para obtener más información, visite el sitio web de Trident https://docs.netapp.com/us-en/trident/index.html["aquí"] .



== Opciones de configuración avanzadas

Esta sección está dedicada a las personalizaciones que los usuarios del mundo real probablemente necesitarían realizar al implementar esta solución en producción, como crear un registro de imágenes privado dedicado o implementar instancias de equilibrador de carga personalizadas.



== Matriz de soporte actual para versiones validadas

Ver https://cloud.google.com/anthos/docs/resources/partner-storage#netapp["aquí"] para la matriz de soporte para versiones validadas.
