---
sidebar: sidebar 
permalink: videos/tanzu-videos.html 
keywords: video, demonstration, deployment, VMware Tanzu with NetApp, NetApp, Tanzu 
summary: Esta página contiene enlaces a vídeos que demuestran algunas de las capacidades descritas en este documento. 
---
= Vea videos sobre VMware Tanzu con NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Explore la integración de VMware Tanzu con NetApp a través de una serie de videos que demuestran capacidades clave como el aprovisionamiento de almacenamiento persistente, la clonación de aplicaciones y la protección de datos mediante Trident.


NOTE: Estas demostraciones se grabaron como una vista previa técnica utilizando la versión 1.3.1 de TKG y la versión 21.12 de Trident Protect.  Consulte la Matriz de soporte para conocer las versiones oficiales compatibles.



== Aprovisionamiento de almacenamiento persistente

.Utilice Trident para aprovisionar almacenamiento persistente en VMware Tanzu - VMware Tanzu con NetApp
video::8db3092b-3468-4754-b2d7-b01200fbb38d[panopto,width=360]


== Clonación de aplicaciones y protección de datos

.Utilice Trident Protect para clonar aplicaciones en VMware Tanzu - VMware Tanzu con NetApp
video::01aff358-a0a2-4c4f-9062-b01200fb9abd[panopto,width=360]